package com.abc

import eu.swdev.web.form.{FieldState, Form}
import eu.swdev.i18n.Resource
import play.api.Application
import eu.swdev.play.form.StdFormResourceApi

@Form
object F {
  val f1 = field[Int].ge(1).le(10)
  val f2 = field[Boolean].addMCheck(m => if (!m) Some(Error("must be checked")) else None)
  val f3 = field[Seq[Int]].enum(Seq(1, 2, 3))
  val f4 = field[Int].enum(Seq(1, 2, 3))
  val f5 = field[Option[Int]].enum(Seq(1, 2, 3))
  val f6 = field[String]
  val f7 = field[Option[String]].enum(Seq("default", "primary", "success", "info", "warning", "danger", "link"))
  val f8 = field[Double].ge(0).le(1)
  val f9 = field[String].enum(Seq("a", "b", "c"))
  val f10 = field[Seq[String]].enum(Seq("a", "b", "c"))
}

/**
 * Contains the resources that are used when rendering forms.
 *
 * The class is a Play plugin. It implements the [[eu.swdev.play.form.FormResourceApi]] and is used by the
 * [[eu.swdev.play.form.FormResource]] object.
 *
 * The abstract methods in the [[eu.swdev.play.form.StdFormResourceApi]] trait are implemented by the methods that
 * are generated by the `@Resource` annotation.
 */
@Resource(resourcePath = "form/form-resource")
class FormResourceApiImpl(app: Application) extends StdFormResourceApi